#!/bin/bash

source ~/bin/proxy.config

AUTOSSH_MONITOR_PORT=20000

function __help() {
    echo 'usage: 
    proxy [run|show|check|log]
example: 
    proxy run   # run proxy
    proxy show  # show proxy information
    proxy check # check proxy status
    proxy log   # show proxy log'
}

function __show() {
    OUTPUT=`ps aux|grep "autossh.*$AUTOSSH_MONITOR_PORT"|grep -v "grep"`
    if [[ -n $OUTPUT ]]; then
        echo "$OUTPUT"
    else
        echo 'PROXY_NOT_WORKING';
    fi
}

# options for autossh:
# -M      specifies the base monitoring port to use.
# -f      run in background (autossh handles this, and does not pass it to ssh.)
#
# options for ssh:
# -q      Quiet mode.
# -T      Disable pseudo-tty allocation.
# -f      Requests ssh to go to background just before command execution.
# -n      Redirects stdin from /dev/null (actually, prevents reading from stdin).  This must be used when ssh is run in the background.
# -N      Do not execute a remote command.  This is useful for just forwarding ports (protocol version 2 only).
# -g      Allows remote hosts to connect to local forwarded ports.
# -D port Specifies a local dynamic application-level port forwarding.

function __start() {
    echo 'try to connect remote host...'
    autossh -M $AUTOSSH_MONITOR_PORT -f -qTnNg -D $PORT $HOST
    __show
}

function __check() {
    CMD="curl $CHECKURL --socks5 "127.0.0.1:$PORT" -s"
    echo "try to connect proxy 127.0.0.1:$PORT..."
    RESPONSE=`$CMD`
    if [[ -n $RESPONSE ]]; then
        TIME=`date +'%Y-%m-%d %H:%M:%S'`
        echo $RESPONSE
        echo "$TIME | PROXY_IS_WORKING" >> $LOGPATH
    else
        TIME=`date +'%Y-%m-%d %H:%M:%S'`
        echo 'not working...'
        echo "$TIME | PROXY_NOT_WORKING" >> $LOGPATH
    fi
}


if [[ $# -eq 0 ]]; then
    __help
else
    ACTION=$1
    case $ACTION in
        'run')
            __start
            ;;
        'show')
            __show
            ;;
        'check')
            __check
            ;;
        'log')
            tail -n 10 $LOGPATH
            ;;
        *)
            __help
            ;;
    esac
fi


