#!/bin/bash


INCLUDE=""

echo 'Search special filetype(enter to skip)?'
read -p "[php/js/css, etc] : " FILETYPE

if [ -n $FILETYPE ]; then
	if [ "$FILETYPE" \> 64 ]; then
		INCLUDE="--include=*.$FILETYPE"
	fi
fi

# --exclude=GLOB Skip files whose base name matches GLOB (using wildcard matching)
# --exclude-dir=DIR Exclude directories matching the pattern DIR from recursive searches
# --include=GLOB Search only files whose base name matches GLOB (using wildcard matching as described under --exclude)
# -I Process a binary file as if it did not contain matching data
# --color=(never, always, or auto) make the output beautiful

#grep $* --exclude=*.{png,jpg,gif,swp} -I $INCLUDE | grep -v '.svn'
grep $* --exclude=*.{png,jpg,gif,swp} --exclude-dir=.{svn,git} -I $INCLUDE --color=auto



